---
title: "NYC Restaurants Inspection Plots"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


Let's load the NYC Restaurant Inspections dataset and focus on Manhattan restautants data.

```{r}
data("rest_inspec")

rest_inspec = rest_inspec |> 
  rename(borough = boro,
         name = dba) |> 
  filter(borough != "0",
         !is.na(score)) |> 
  select(camis, name, borough, zipcode, street, cuisine_description, 
         score, grade, longitude, latitude, inspection_date) |>
  distinct(camis, inspection_date, .keep_all = TRUE) |> 
  group_by(camis) |>
  mutate(avg_score = mean(score, na.rm = TRUE),
         n_inspections = sum(!is.na(score), na.rm = TRUE),
         cuisine_description = case_when(
           str_detect(cuisine_description, regex("Latin", ignore_case = TRUE)) ~ "Latin",
           str_detect(cuisine_description, regex("Bottled beverages, including water, sodas, juices", ignore_case = TRUE)) ~ "Bottled beverages", 
           TRUE ~ cuisine_description)
         ) |> 
  ungroup()

manhattan_rest = rest_inspec |> 
  filter(borough == "Manhattan",
         latitude != 0,
         longitude != 0,
         )


```

Scatter Plot

```{r}
manhattan_rest |> 
  mutate(
    label = str_c("Average Violation Score: ", round(avg_score), "\nStreet: ", street, "\nName: ", name, "\nCuisine: ", cuisine_description)
  ) |> 
  distinct(camis, avg_score, .keep_all = TRUE) |> 
  filter(
    avg_score > 0,
    avg_score <= 30) |> 
  slice_sample(prop = 0.4) |> 
  plot_ly(
    x = ~longitude, 
    y = ~latitude, 
    color = ~avg_score,
    text = ~ label,
    type = "scatter", 
    mode = "markers",
    alpha = 0.8
    )
```

Boxplot

```{r}
manhattan_rest |> 
  mutate(
    grade = fct_reorder(grade, avg_score, .na_rm = TRUE),
  ) |> 
  plot_ly(
    x = ~grade, y = ~avg_score, color = ~grade,
    type = "box", colors = "viridis"
  ) |> 
  layout(
    xaxis = list(title = "Health Grade Level in Manhattan"),
    yaxis = list(title = "Average Violation Score")
  )
```

```{r}
manhattan_rest |> 
  mutate(
     cuisine_description = fct_reorder(cuisine_description, avg_score, .na_rm = TRUE),
  ) |> 
  plot_ly(
    x = ~cuisine_description, 
    y = ~avg_score, 
    color = ~cuisine_description,
    type = "box", 
    colors = "viridis"
    ) |> 
  layout(
    xaxis = list(title = "Restaurant Cuisine type in Manhattan"),
    yaxis = list(title = "Average Violation Score")
  )
```


Bar chart

```{r}
manhattan_rest |> 
  count(grade) |> 
  mutate(
    grade = fct_reorder(grade, n)
  ) |> 
  plot_ly(
    x = ~grade, y = ~n, color = ~grade,
    type = "bar"
  ) |> 
  layout(
    xaxis = list(title = "Health Grade Level"),
    yaxis = list(title = "Frequency in Manhattan")
  )
```


```{r}
rest_inspec |> 
  group_by(borough) |> 
  summarize(count = n_distinct(camis), .groups = "drop") |> 
  mutate(
    borough = fct_reorder(borough, count)
  ) |> 
  plot_ly(
    x = ~borough, y = ~count, color = ~borough,
    type = "bar"
    ) |> 
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Number of restaurants")
  )
```


Go back to the [homepage](index.html).

