---
title: "Here are some plots"
author: "Liliang Su"
date: "2025-10-21"
output: html_document
---

Interactive plots


```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


Let's load the Airbnb dataset.

```{r}
data("nyc_airbnb")

nyc_airbnb = nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating, price,
    room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Let's make a scatterplot!!!! But interactive this time.

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating)
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~ label,
    type = "scatter", mode = "markers"
  )
```

